POST http://localhost:2525/imposters
Content-Type: application/json
 
{
  "port": 4556,
  "protocol": "http",
  "stubs": [
 
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/auth"
          }
        },
        {
          "equals": {
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "deepEquals": {
            "body": {
              "username": "user1",
              "password": "pass1"
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "token": "abcd",
              "expires_in": 3600
            }
          }
        }
      ]
    },
 
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/auth"
          }
        },
        {
          "equals": {
            "headers": {
              "Content-Type": "application/json"
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 401,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "invalid_credentials"
            }
          }
        }
      ]
    }
 
  ]
}