POST http://localhost:2525/imposters
Content-Type: application/json
 
{
  "port": 4557,
  "protocol": "http",
  "stubs": [

    {
      "predicates": [
        {
          "equals": {
            "method": "GET",
            "path": "/api/profile"
          }
        },
        {
          "equals": {
            "headers": {
              "Authorization": "Bearer validtoken"
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "username": "user1",
              "email": "user1@example.com",
              "role": "user"
            }
          }
        }
      ]
    },

    {
      "predicates": [
        {
          "equals": {
            "method": "GET",
            "path": "/api/profile"
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 403,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "forbidden"
            }
          }
        }
      ]
    }

  ]
}