POST http://localhost:2525/imposters

{
  "port": 4550,
  "protocol": "http",
  "name": "Exercício 6",
  "stubs": [
    {
      "description": "Exercício 6 - POST /api/users com email específico",
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/users",
            "headers": {
              "Content-Type": "application/json"
            }
          },
          "contains": { "email": "exists@example.com"}
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "email_exists",
              "message": "Email já está a ser utilizado"
            }
          }
        }
      ]
    }
  ]
}

