POST http://localhost:2525/imposters

{
  "port": 4545,
  "protocol": "http",
  "name": "Exercício 1",
  "stubs": [
    {
      "description": "Exercício 1 - GET /api/marcas",
      "predicates": [
        {
          "equals": {
            "method": "GET", 
            "path": "/api/marcas"
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "marcas": ["Toyota", "Audi", "Ford", "Volvo", "Honda"]
            }
          }
        }
      ]
    }
  ]
}

